#' @title Data to estimate quarterly U.S. inflation
#' @description  A novel, high-dimensional dataset built by Koop and Korobilis (2023)
#'               that merges predictors from several mainstream aggregate
#'               macroeconomic and financial data sets. The dataset includes
#'               the FRED-QD dataset of McCracken and Ng (2020),
#'               augment with portfolio data used in Jurado et al. (2015),
#'               stock market predictors from Welch and Goyal (2008),
#'               survey data from University of Michigan consumer surveys,
#'               commodity prices from the World Bank’s Pink Sheet database,
#'               and key macroeconomic indicators from the Federal Reserve Economic Data
#'               for four economies (Canada, Germany, Japan, United Kingdom).
#'               All data are quarterly, and span the period 1960Q1–2021Q4.
#'
#' @format A \link{data.frame} with 248 quarterly observations (rows) and 445 variables (columns).
#' @references
#'
#' Jurado, K., Ludvigson, S. C., and Ng, S. (2015) "Measuring uncertainty."
#' \emph{American Economic Review}, 105 (3): 1177–1216.
#'
#' Koop, G. and Korobilis, D. (2023) "Bayesian dynamic variable selection in high dimensions."
#' \emph{International Economic Review}.
#'
#' McCracken, M., and S. Ng (2020) “FRED-QD: A Quarterly Database for Macroeconomic Research”
#' \emph{National Bureau of Economic Research}, Working Paper 26872.
#'
#' Welch, I. and Goyal, A. (2008) "A comprehensive look at the empirical performance of equity premium prediction."
#' \emph{The Review of Financial Studies}, 21 (4): 1455–1508.
#'
#' @source \url{https://onlinelibrary.wiley.com/doi/full/10.1111/iere.12623}
"inflation_data"


#' @title External Point Forecasts for U.S. inflation (GDP deflator)
#' @description  External point forecasts for quarterly GDP deflator
#'               generated by the MatLab Code from Koop and Korobilis (2023).
#'               Out-of-sample one-step-ahead forecasts are generated
#'               from 1976-Q1 to 2021-Q4.
#'
#' @format A \link{data.frame} with 245 quarterly observations (rows) and 16 forecasting models (columns):
#' \describe{
#'    \item{ARp}{AR(2) with intercept, estimated with OLS}
#'    \item{SBAR}{Bayesian Structural Breaks AR(2)}
#'    \item{UCSV}{Unobserved Components Stochastic Volatility Model}
#'    \item{TVPAR}{Time-Varying Parameter AR Model}
#'    \item{FAC5}{Principal Components Regression using the first five components}
#'    \item{BAG/FAC5}{Regression estimated using Bagging using the first five components}
#'    \item{GPR/FAC5}{Gaussian Process Regression using the first five components}
#'    \item{DMA/FAC5}{Dynamic Model Averaging using the first five components}
#'    \item{TVD/FAC5}{Time-Varying Dimension Model using the first five components}
#'    \item{VBDVS/FAC5}{Variational Bayes Dynamic Variable Selection Algorithm using the first five components}
#'    \item{SSVS/FAC60}{Stochastic Search Variable Selection algorithm using the first 60 components}
#'    \item{ELN/FAC60}{Elastic Net using the first 60 components}
#'    \item{VBDVS/FAC60}{Variational Bayes Dynamic Variable Selection Algorithm using the first 60 components}
#'    \item{ELN/X}{Elastic Net with all 439 predictors}
#'    \item{PLS/X}{Partial Least Squares with all 439 predictors}
#'    \item{VBDVS/X}{Variational Bayes Dynamic Variable Selection Algorithm with all 439 predictors}
#' }
#' @references
#'
#' Koop, G. and Korobilis, D. (2023) "Bayesian dynamic variable selection in high dimensions."
#' \emph{International Economic Review}.
#'
#' @source \url{https://onlinelibrary.wiley.com/doi/full/10.1111/iere.12623}
"Ext_PF_GDPCTPI"


#' @title External Point Forecasts for U.S. inflation (PCE deflator)
#' @description  External point forecasts for quarterly PCE deflator
#'               generated by the MatLab Code from Koop and Korobilis (2023).
#'               Out-of-sample one-step-ahead forecasts are generated
#'               from 1976-Q1 to 2021-Q4.
#'
#' @format A \link{data.frame} with 245 quarterly observations (rows) and 16 forecasting models (columns):
#' \describe{
#'    \item{ARp}{AR(2) with intercept, estimated with OLS}
#'    \item{SBAR}{Bayesian Structural Breaks AR(2)}
#'    \item{UCSV}{Unobserved Components Stochastic Volatility Model}
#'    \item{TVPAR}{Time-Varying Parameter AR Model}
#'    \item{FAC5}{Principal Components Regression using the first five components}
#'    \item{BAG/FAC5}{Regression estimated using Bagging using the first five components}
#'    \item{GPR/FAC5}{Gaussian Process Regression using the first five components}
#'    \item{DMA/FAC5}{Dynamic Model Averaging using the first five components}
#'    \item{TVD/FAC5}{Time-Varying Dimension Model using the first five components}
#'    \item{VBDVS/FAC5}{Variational Bayes Dynamic Variable Selection Algorithm using the first five components}
#'    \item{SSVS/FAC60}{Stochastic Search Variable Selection algorithm using the first 60 components}
#'    \item{ELN/FAC60}{Elastic Net using the first 60 components}
#'    \item{VBDVS/FAC60}{Variational Bayes Dynamic Variable Selection Algorithm using the first 60 components}
#'    \item{ELN/X}{Elastic Net with all 439 predictors}
#'    \item{PLS/X}{Partial Least Squares with all 439 predictors}
#'    \item{VBDVS/X}{Variational Bayes Dynamic Variable Selection Algorithm with all 439 predictors}
#' }
#' @references
#'
#' Koop, G. and Korobilis, D. (2023) "Bayesian dynamic variable selection in high dimensions."
#' \emph{International Economic Review}.
#'
#' @source \url{https://onlinelibrary.wiley.com/doi/full/10.1111/iere.12623}
"Ext_PF_PCECTPI"


#' @title External Point Forecasts for U.S. inflation (Total CPI)
#' @description  External point forecasts for quarterly Total CPI
#'               generated by the MatLab Code from Koop and Korobilis (2023).
#'               Out-of-sample one-step-ahead forecasts are generated
#'               from 1976-Q1 to 2021-Q4.
#'
#' @format A \link{data.frame} with 245 quarterly observations (rows) and 16 forecasting models (columns):
#' \describe{
#'    \item{ARp}{AR(2) with intercept, estimated with OLS}
#'    \item{SBAR}{Bayesian Structural Breaks AR(2)}
#'    \item{UCSV}{Unobserved Components Stochastic Volatility Model}
#'    \item{TVPAR}{Time-Varying Parameter AR Model}
#'    \item{FAC5}{Principal Components Regression using the first five components}
#'    \item{BAG/FAC5}{Regression estimated using Bagging using the first five components}
#'    \item{GPR/FAC5}{Gaussian Process Regression using the first five components}
#'    \item{DMA/FAC5}{Dynamic Model Averaging using the first five components}
#'    \item{TVD/FAC5}{Time-Varying Dimension Model using the first five components}
#'    \item{VBDVS/FAC5}{Variational Bayes Dynamic Variable Selection Algorithm using the first five components}
#'    \item{SSVS/FAC60}{Stochastic Search Variable Selection algorithm using the first 60 components}
#'    \item{ELN/FAC60}{Elastic Net using the first 60 components}
#'    \item{VBDVS/FAC60}{Variational Bayes Dynamic Variable Selection Algorithm using the first 60 components}
#'    \item{ELN/X}{Elastic Net with all 439 predictors}
#'    \item{PLS/X}{Partial Least Squares with all 439 predictors}
#'    \item{VBDVS/X}{Variational Bayes Dynamic Variable Selection Algorithm with all 439 predictors}
#' }
#' @references
#'
#' Koop, G. and Korobilis, D. (2023) "Bayesian dynamic variable selection in high dimensions."
#' \emph{International Economic Review}.
#'
#' @source \url{https://onlinelibrary.wiley.com/doi/full/10.1111/iere.12623}
"Ext_PF_CPIAUCSL"


#' @title External Point Forecasts for U.S. inflation (Core CPI)
#' @description  External point forecasts for quarterly Core CPI
#'               generated by the MatLab Code from Koop and Korobilis (2023).
#'               Out-of-sample one-step-ahead forecasts are generated
#'               from 1976-Q1 to 2021-Q4.
#'
#' @format A \link{data.frame} with 245 quarterly observations (rows) and 16 forecasting models (columns):
#' \describe{
#'    \item{ARp}{AR(2) with intercept, estimated with OLS}
#'    \item{SBAR}{Bayesian Structural Breaks AR(2)}
#'    \item{UCSV}{Unobserved Components Stochastic Volatility Model}
#'    \item{TVPAR}{Time-Varying Parameter AR Model}
#'    \item{FAC5}{Principal Components Regression using the first five components}
#'    \item{BAG/FAC5}{Regression estimated using Bagging using the first five components}
#'    \item{GPR/FAC5}{Gaussian Process Regression using the first five components}
#'    \item{DMA/FAC5}{Dynamic Model Averaging using the first five components}
#'    \item{TVD/FAC5}{Time-Varying Dimension Model using the first five components}
#'    \item{VBDVS/FAC5}{Variational Bayes Dynamic Variable Selection Algorithm using the first five components}
#'    \item{SSVS/FAC60}{Stochastic Search Variable Selection algorithm using the first 60 components}
#'    \item{ELN/FAC60}{Elastic Net using the first 60 components}
#'    \item{VBDVS/FAC60}{Variational Bayes Dynamic Variable Selection Algorithm using the first 60 components}
#'    \item{ELN/X}{Elastic Net with all 439 predictors}
#'    \item{PLS/X}{Partial Least Squares with all 439 predictors}
#'    \item{VBDVS/X}{Variational Bayes Dynamic Variable Selection Algorithm with all 439 predictors}
#' }
#' @references
#'
#' Koop, G. and Korobilis, D. (2023) "Bayesian dynamic variable selection in high dimensions."
#' \emph{International Economic Review}.
#'
#' @source \url{https://onlinelibrary.wiley.com/doi/full/10.1111/iere.12623}
"Ext_PF_CPILFESL"