# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

init_dsc <- function(number_forecasts) {
    .Call(`_hdflex_init_dsc`, number_forecasts)
}

forget_dsc <- function(weights, gamma) {
    .Call(`_hdflex_forget_dsc`, weights, gamma)
}

active_models_dsc <- function(weights, psi) {
    .Call(`_hdflex_active_models_dsc`, weights, psi)
}

matrix_subset_idx <- function(mat, col_idx, t) {
    .Call(`_hdflex_matrix_subset_idx`, mat, col_idx, t)
}

agg_density_dsc <- function(active_weights, oos_target_var, oos_forecast_tvp, oos_variance_tvp, idx_sub, t) {
    .Call(`_hdflex_agg_density_dsc`, active_weights, oos_target_var, oos_forecast_tvp, oos_variance_tvp, idx_sub, t)
}

update_dsc <- function(weights, oos_target_var, oos_forecast_tvp, oos_variance_tvp, n_models, t) {
    .Call(`_hdflex_update_dsc`, weights, oos_target_var, oos_forecast_tvp, oos_variance_tvp, n_models, t)
}

dsc_loop <- function(weights, gamma, psi, oos_target_var, oos_forecast_tvp, oos_variance_tvp, len_para_grid, oos_length, n_models) {
    .Call(`_hdflex_dsc_loop`, weights, gamma, psi, oos_target_var, oos_forecast_tvp, oos_variance_tvp, len_para_grid, oos_length, n_models)
}

init_tvc_ <- function(y, S, n_sim_sig, sample_length, lambda_grid, kappa_grid) {
    .Call(`_hdflex_init_tvc_`, y, S, n_sim_sig, sample_length, lambda_grid, kappa_grid)
}

tvc_model_ <- function(y_t, s_t_j, s_tplus1_j, lambda, kappa, theta, cov_mat, h) {
    .Call(`_hdflex_tvc_model_`, y_t, s_t_j, s_tplus1_j, lambda, kappa, theta, cov_mat, h)
}

tvc_model_cand_ <- function(y_t, s_t, s_tplus1, lambda_grid, kappa_grid, theta_all, cov_mat_all, h_all) {
    .Call(`_hdflex_tvc_model_cand_`, y_t, s_t, s_tplus1, lambda_grid, kappa_grid, theta_all, cov_mat_all, h_all)
}

dsc_init_ <- function(n_cands, n_combs, n_gamma, na_idx) {
    .Call(`_hdflex_dsc_init_`, n_cands, n_combs, n_gamma, na_idx)
}

dsc_active_models_ <- function(dpll_cands_gamma, psi) {
    .Call(`_hdflex_dsc_active_models_`, dpll_cands_gamma, psi)
}

dsc_agg_density_ <- function(active_weights, forecast_tvc_t, variance_tvc_t, idx_sub) {
    .Call(`_hdflex_dsc_agg_density_`, active_weights, forecast_tvc_t, variance_tvc_t, idx_sub)
}

dsc_dpll_cands_ <- function(dpll_cands_gamma, y_t, forecast_tvc_t, variance_tvc_t, gamma, method, risk_aversion_ = NULL, min_weight_ = NULL, max_weight_ = NULL) {
    invisible(.Call(`_hdflex_dsc_dpll_cands_`, dpll_cands_gamma, y_t, forecast_tvc_t, variance_tvc_t, gamma, method, risk_aversion_, min_weight_, max_weight_))
}

rank_comb_ <- function(dpll_combs, mu_comb_vec, variance_comb_vec) {
    .Call(`_hdflex_rank_comb_`, dpll_combs, mu_comb_vec, variance_comb_vec)
}

dsc_dpll_comb_ <- function(dpll_combs, y_t, forecasts_comb, variances_comb, delta, method, risk_aversion_ = NULL, min_weight_ = NULL, max_weight_ = NULL) {
    invisible(.Call(`_hdflex_dsc_dpll_comb_`, dpll_combs, y_t, forecasts_comb, variances_comb, delta, method, risk_aversion_, min_weight_, max_weight_))
}

dsc_loop_ <- function(dpll_cands, dpll_combs, gamma_grid, psi_grid, y_t, forecast_tvc_t, variance_tvc_t, delta, method, equal_weight, risk_aversion_ = NULL, min_weight_ = NULL, max_weight_ = NULL) {
    .Call(`_hdflex_dsc_loop_`, dpll_cands, dpll_combs, gamma_grid, psi_grid, y_t, forecast_tvc_t, variance_tvc_t, delta, method, equal_weight, risk_aversion_, min_weight_, max_weight_)
}

stsc_loop <- function(y, X_, Ext_F_, sample_length, lambda_grid, kappa_grid, burn_in_tvc, gamma_grid, psi_grid, delta, burn_in_dsc, method, equal_weight, risk_aversion_ = NULL, min_weight_ = NULL, max_weight_ = NULL) {
    .Call(`_hdflex_stsc_loop`, y, X_, Ext_F_, sample_length, lambda_grid, kappa_grid, burn_in_tvc, gamma_grid, psi_grid, delta, burn_in_dsc, method, equal_weight, risk_aversion_, min_weight_, max_weight_)
}

init_tvc <- function(y_var, x_var, sample_length) {
    .Call(`_hdflex_init_tvc`, y_var, x_var, sample_length)
}

init_tvc_forecast <- function(y_var, x_var, sample_length) {
    .Call(`_hdflex_init_tvc_forecast`, y_var, x_var, sample_length)
}

tvc_model <- function(y_var, x_var, i, lambda, kappa, theta, cov_mat, h) {
    .Call(`_hdflex_tvc_model`, y_var, x_var, i, lambda, kappa, theta, cov_mat, h)
}

tvc_model_loop <- function(y_var, x_var, lambda, kappa, theta, cov_mat, h, ts_length, drop_length, max_length) {
    .Call(`_hdflex_tvc_model_loop`, y_var, x_var, lambda, kappa, theta, cov_mat, h, ts_length, drop_length, max_length)
}

