# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dsc_ <- function(y, point_forecasts, variance_forecasts, gamma_grid, psi_grid, delta, burn_in, burn_in_dsc, metric, equal_weight, incl_, portfolio_params_) {
    .Call(`_hdflex_dsc_`, y, point_forecasts, variance_forecasts, gamma_grid, psi_grid, delta, burn_in, burn_in_dsc, metric, equal_weight, incl_, portfolio_params_)
}

stsc_loop_ <- function(y, X_, Ext_F_, init, lambda_grid, kappa_grid, bias, gamma_grid, psi_grid, delta, burn_in, burn_in_dsc, metric, equal_weight, incl_, portfolio_params_) {
    .Call(`_hdflex_stsc_loop_`, y, X_, Ext_F_, init, lambda_grid, kappa_grid, bias, gamma_grid, psi_grid, delta, burn_in, burn_in_dsc, metric, equal_weight, incl_, portfolio_params_)
}

stsc_loop_par_ <- function(y, X_, Ext_F_, init, lambda_grid, kappa_grid, bias, gamma_grid, psi_grid, delta, burn_in, burn_in_dsc, metric, equal_weight, incl_, n_threads, portfolio_params_) {
    .Call(`_hdflex_stsc_loop_par_`, y, X_, Ext_F_, init, lambda_grid, kappa_grid, bias, gamma_grid, psi_grid, delta, burn_in, burn_in_dsc, metric, equal_weight, incl_, n_threads, portfolio_params_)
}

tvc_ <- function(y, X_, Ext_F_, init, lambda_grid, kappa_grid, bias) {
    .Call(`_hdflex_tvc_`, y, X_, Ext_F_, init, lambda_grid, kappa_grid, bias)
}

